import type { Case, ChecklistItem, Document, Notification, Payment, Profile, ServicePricing } from "@/types/database";

const now = new Date().toISOString();

export const mockProfile: Profile = {
  id: "11111111-1111-1111-1111-111111111111",
  full_name: "Andres Bedoya",
  email: "andres@fintax.nl",
  phone: "+31 6 87654321",
  date_of_birth: "1993-04-18",
  bsn_encrypted: null,
  nationality: "Colombian",
  country_of_origin: "CO",
  address_street: "Demo Straat 10",
  address_city: "Rotterdam",
  address_postal_code: "3011AA",
  address_country: "NL",
  preferred_language: "en",
  avatar_url: null,
  theme: "dark",
  notification_email: true,
  notification_in_app: true,
  onboarding_completed: true,
  role: "user",
  created_at: now,
  updated_at: now,
};

export const mockCases: Case[] = [
  {
    id: "case-tax-2025",
    user_id: mockProfile.id,
    case_type: "tax_return_p",
    status: "in_review",
    display_name: "Aangifte inkomstenbelasting 2025",
    tax_year: 2025,
    deadline: "2026-05-12",
    estimated_refund: 1286,
    actual_refund: null,
    wizard_data: {},
    wizard_completed: false,
    machtiging_status: "requested",
    machtiging_code: null,
    stripe_payment_id: null,
    assigned_admin: null,
    notes_internal: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "case-benefits-2026",
    user_id: mockProfile.id,
    case_type: "zorgtoeslag",
    status: "pending_payment",
    display_name: "Zorgtoeslag + Huurtoeslag 2026",
    tax_year: 2026,
    deadline: "2026-12-31",
    estimated_refund: 847,
    actual_refund: null,
    wizard_data: {},
    wizard_completed: true,
    machtiging_status: "not_started",
    machtiging_code: null,
    stripe_payment_id: null,
    assigned_admin: null,
    notes_internal: null,
    created_at: now,
    updated_at: now,
  },
];

export const mockChecklistByCase: Record<string, ChecklistItem[]> = {
  "case-tax-2025": [
    {
      id: "cli-1",
      case_id: "case-tax-2025",
      label: "Passport / ID",
      label_key: null,
      description: "Photo or scan of valid ID",
      is_document_upload: true,
      is_completed: true,
      completed_at: now,
      completed_by: mockProfile.id,
      document_id: "doc-1",
      sort_order: 1,
      created_at: now,
    },
    {
      id: "cli-2",
      case_id: "case-tax-2025",
      label: "Annual income statements",
      label_key: null,
      description: "Jaaropgave / salary slips",
      is_document_upload: true,
      is_completed: true,
      completed_at: now,
      completed_by: mockProfile.id,
      document_id: "doc-2",
      sort_order: 2,
      created_at: now,
    },
    {
      id: "cli-3",
      case_id: "case-tax-2025",
      label: "Housing costs and address history",
      label_key: null,
      description: "Contract + months of residence",
      is_document_upload: false,
      is_completed: false,
      completed_at: null,
      completed_by: null,
      document_id: null,
      sort_order: 3,
      created_at: now,
    },
  ],
  "case-benefits-2026": [
    {
      id: "cli-b1",
      case_id: "case-benefits-2026",
      label: "Health insurance policy",
      label_key: null,
      description: "Policy statement showing coverage in NL",
      is_document_upload: true,
      is_completed: false,
      completed_at: null,
      completed_by: null,
      document_id: null,
      sort_order: 1,
      created_at: now,
    },
  ],
};

export const mockDocumentsByCase: Record<string, Document[]> = {
  "case-tax-2025": [
    {
      id: "doc-1",
      case_id: "case-tax-2025",
      user_id: mockProfile.id,
      checklist_item_id: "cli-1",
      file_name: "passport.pdf",
      file_path: "demo/passport.pdf",
      file_size: 420000,
      mime_type: "application/pdf",
      status: "approved",
      review_notes: "Readable",
      reviewed_by: mockProfile.id,
      reviewed_at: now,
      created_at: now,
    },
    {
      id: "doc-2",
      case_id: "case-tax-2025",
      user_id: mockProfile.id,
      checklist_item_id: "cli-2",
      file_name: "jaaropgave-2025.pdf",
      file_path: "demo/jaaropgave-2025.pdf",
      file_size: 625000,
      mime_type: "application/pdf",
      status: "under_review",
      review_notes: null,
      reviewed_by: null,
      reviewed_at: null,
      created_at: now,
    },
  ],
  "case-benefits-2026": [],
};

export const mockNotifications: Notification[] = [
  {
    id: "ntf-1",
    user_id: mockProfile.id,
    case_id: "case-tax-2025",
    title: "Document approved",
    message: "Passport approved. Upload housing documents next.",
    type: "success",
    is_read: false,
    link: "/tax-return/case-tax-2025",
    created_at: now,
  },
  {
    id: "ntf-2",
    user_id: mockProfile.id,
    case_id: "case-benefits-2026",
    title: "Payment pending",
    message: "Complete payment to start benefits filing.",
    type: "action_required",
    is_read: false,
    link: "/benefits/case-benefits-2026",
    created_at: now,
  },
];

export const mockPayments: Payment[] = [
  {
    id: "pay-1",
    user_id: mockProfile.id,
    case_id: "case-benefits-2026",
    stripe_payment_intent_id: "pi_demo_123",
    stripe_checkout_session_id: "cs_demo_123",
    amount: 39,
    currency: "EUR",
    status: "pending",
    payment_method: "ideal",
    created_at: now,
    updated_at: now,
  },
];

export const mockServicePricing: ServicePricing[] = [
  { id: "sp1", case_type: "tax_return_p", name: "Form P", description: "Residents", price: 89, is_active: true, created_at: now },
  { id: "sp2", case_type: "tax_return_m", name: "Form M", description: "Migration", price: 119, is_active: true, created_at: now },
  { id: "sp3", case_type: "tax_return_c", name: "Form C", description: "Non-resident", price: 99, is_active: true, created_at: now },
  { id: "sp4", case_type: "tax_return_w", name: "ZZP", description: "Self-employed", price: 149, is_active: true, created_at: now },
  { id: "sp5", case_type: "btw_declaration", name: "BTW", description: "VAT declaration", price: 59, is_active: true, created_at: now },
];

export function getMockCase(caseId: string) {
  return mockCases.find((item) => item.id === caseId) ?? null;
}
